name: checks
on:
  - pull_request
  - push
jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
