name: checks
on:
  - pull_request
jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
