name: devbuild

concurrency: 
  group: "build-1.17"
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: zulu
    - name: Build
      run: |
        chmod +x ./gradlew
        ./gradlew build
    - name: Remove *-dev.jar
      run: rm ./build/libs/*-dev.jar
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-1.17"
        prerelease: false
        title: "1.17 Build"
        files: |
          ./build/libs/*.jar
